Add missing permissions for PR creation
Changeset action fails to create the _Version packages_ PR with the following error:
```log
creating pull request
Error: HttpError: Resource not accessible by integration - https://docs.github.com/rest/pulls/pulls#create-a-pull-request
Error: Resource not accessible by integration - https://docs.github.com/rest/pulls/pulls#create-a-pull-request
```

Fix per https://github.com/changesets/action/issues/199#issuecomment-2012315190